version: "3.9"

services:
  back-end:
    depends_on:
      - mongodb
    container_name: music-streaming-back-end
    build: ./back-end
    working_dir: /code/app
    command: uvicorn server.app:app --proxy-headers --host 0.0.0.0 --port 8090 --reload
    volumes:
      - ./back-end/app:/code/app
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=music
      
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=music
      - MONGO_INITDB_ROOT_PASSWORD=music
  
  front-end:
    build: ./front-end
    volumes:
      - './front-end:/usr/src/app' 
    ports: 
      - '4200:4200'
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --poll 2000"