version: "3.9"

services:
  back-end:
    container_name: music-streaming-back-end
    build: ./back-end
    working_dir: /code/app
    command: uvicorn server.app:app --proxy-headers --host 0.0.0.0 --port 8090 --reload
    volumes:
      - ./back-end/app:/code/app
    ports:
      - "8090:8090"
    restart: on-failure
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=music
    #   - MONGO_INITDB_ROOT_PASSWORD=music