USER_NR = 3
USER_AGE_MIN = 12
USER_AGE_MAX = 70
USER_PLAYLIST_NR_MIN = 1
USER_PLAYLIST_NR_MAX = 3
USER_PLAYLIST_LIBRARY_NR_MIN = 1
USER_PLAYLIST_LIBRARY_NR_MAX = 3
USER_ARTIST_LIBRARY_NR_MIN = 1
USER_ARTIST_LIBRARY_NR_MAX = 3
USER_ALBUM_LIBRARY_NR_MIN = 2
USER_ALBUM_LIBRARY_NR_MAX = 5
USER_SONG_LIBRARY_NR_MIN = 5
USER_SONG_LIBRARY_NR_MAX = 20
USER_SONG_LISTENING_NR_MIN = 0
USER_SONG_LISTENING_NR_MAX = 3

ARTIST_NR = 5
ARTIST_ALBUMS_NR_MIN = 1
ARTIST_ALBUMS_NR_MAX = 3

ALBUM_LABELS = ["Universal Music Group", "Sony Music", "Warner Music Group"]
ALBUM_TYPES = ["SINGLE", "EXTENDED_PLAY", "LONGPLAY"]
ALBUM_GENRES = [
    "Blues",
    "Classical",
    "Country",
    "Disco",
    "Hiphop",
    "Jazz",
    "Metal",
    "Pop",
    "Reggae",
    "Rock",
]
SINGLE_SONG_NR = 1
EP_SONG_NR_MIN = 2
EP_SONG_NR_MAX = 5
LP_SONG_NR_MIN = 6
LP_SONG_NR_MAX = 10

SONG_LENGTH_MIN = 120
SONG_LENGTH_MAX = 300

PLAYLIST_SONG_NR_MIN = 5
PLAYLIST_SONG_NR_MAX = 20
